"""empty message

Revision ID: d532e600652f
Revises: 
Create Date: 2018-10-22 14:11:07.009952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd532e600652f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('returns')
    op.drop_table('orders')
    op.add_column('feeds', sa.Column('source_kindid', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('source_objectid', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('source_projectid', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('useravatar', sa.String(length=200), nullable=True))
    op.add_column('feeds', sa.Column('userid', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('username', sa.String(length=100), nullable=True))
    op.drop_constraint('feeds_ibfk_2', 'feeds', type_='foreignkey')
    op.drop_constraint('feeds_ibfk_1', 'feeds', type_='foreignkey')
    op.drop_column('feeds', 'divider')
    op.drop_column('feeds', 'file_id')
    op.drop_column('feeds', 'sourceid')
    op.drop_column('feeds', 'avatar_url')
    op.drop_column('feeds', 'user_id')
    op.drop_column('feeds', 'kind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('kind', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('avatar_url', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('feeds', sa.Column('sourceid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('file_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('divider', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_foreign_key('feeds_ibfk_1', 'feeds', 'users', ['user_id'], ['id'])
    op.create_foreign_key('feeds_ibfk_2', 'feeds', 'files', ['file_id'], ['id'])
    op.drop_column('feeds', 'username')
    op.drop_column('feeds', 'userid')
    op.drop_column('feeds', 'useravatar')
    op.drop_column('feeds', 'source_projectid')
    op.drop_column('feeds', 'source_objectid')
    op.drop_column('feeds', 'source_kindid')
    op.create_table('orders',
    sa.Column('Row ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Order ID', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('Order Date', sa.DATE(), nullable=True),
    sa.Column('Ship Date', sa.DATE(), nullable=True),
    sa.Column('Ship Mode', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('Customer ID', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('Customer Name', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('Segment', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('Country', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=17), nullable=True),
    sa.Column('State', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Postal Code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Region', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('Product ID', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('Category', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('Sub-Category', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('Product Name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Sales', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('Quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Discount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('Profit', mysql.DOUBLE(asdecimal=True), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('returns',
    sa.Column('Returned', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('Order ID', mysql.VARCHAR(length=15), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('people',
    sa.Column('Person', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Region', mysql.VARCHAR(length=10), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
